name: timer_5217
description: A minimalistic 52/17 timer app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^9.4.0
  flutter_modular: ^4.5.1+1
  flutter_native_timezone: ^2.0.0
  freezed_annotation: ^1.1.0
  shared_preferences: ^2.0.13
  system_settings: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  freezed: ^1.1.1
  json_serializable: ^6.1.3
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon_ios.png"
